/Mode Full
/Geometry/Bambino2/Construct
/Geometry/Bambino2/UpstreamOffset 3.4 cm
/Geometry/Bambino2/DownstreamOffset 2.6 cm
/Geometry/SeGA/Offset 3.1 cm
/Geometry/Target/Construct
/Geometry/Target/StandardTarget 48Ti
/Geometry/Update
#
/Reaction/ProjectileZ 48
/Reaction/ProjectileA 106
/Reaction/RecoilZ 22
/Reaction/RecoilA 48
/Reaction/SendToDownstreamJanus
#
/Beam/Energy 318 MeV
#
/Excitation/Projectile/LevelScheme Examples/LevelSchemes/Full/cd106.lvl
/Excitation/Projectile/Probabilities Examples/Probabilities/cd106_on_ti48.prb
/Excitation/Projectile/StatisticalTensors Examples/StatisticalTensors/cd106_on_ti48.ten
/Excitation/Recoil/LevelScheme Examples/LevelSchemes/Full/ti48.lvl
/Excitation/Recoil/Probabilities Examples/Probabilities/ti48_by_cd106.prb
/Excitation/Recoil/StatisticalTensors Examples/StatisticalTensors/ti48_by_cd106.ten
#
/Output/FileName full.dat
#
/run/beamOn 100000
