/Mode Scattering
/Geometry/Bambino2/UpstreamOffset 3.6 cm
/Geometry/Bambino2/DownstreamOffset 2.6 cm
/Geometry/SeGA/Offset 3.1 cm
/Geometry/Target/StandardTarget 208Pb
/Geometry/Update
#
/Reaction/ProjectileZ 48
/Reaction/ProjectileA 106
/Reaction/RecoilZ 82
/Reaction/RecoilA 208
/Reaction/DeltaE 0.0 MeV
/Reaction/SendToJanus
#
/Beam/Energy 450 MeV
#
/Output/FileName scattering.dat
#
/run/beamOn 100000
